### ISSUE TITLE
`generate-mask.ts` 生成的两个文件有什么区别呢？可以用于解密酷狗哪些类型的文件？

### ISSUE THREAD

**Issue by nukemiko** [jixunmoe/kugou-crypto#2]

**Comment by jixunmoe** [comment]
写着 v2 的是 `vpr` 格式的，其它的是 `kgm` 的。

**Comment by jixunmoe** [comment]
你如果是想给 Python 用的话，看这个根据索引生成对应 mask 的代码可能会容易理解一些：

https://github.com/jixunmoe/kugou-crypto/blob/0335b86db77f3fa11e1d7ae776bd2cd10817d7a0/src/utils/getMaskByteAtOffset.ts#L3-L18

**Comment by nukemiko** [comment]
> 你如果是想给 Python 用的话，看这个根据~索引~文件偏移生成对应 mask 的代码可能会容易理解一些：
> 
> https://github.com/jixunmoe/kugou-crypto/blob/0335b86db77f3fa11e1d7ae776bd2cd10817d7a0/src/utils/getMaskByteAtOffset.ts#L3-L18

好的，我去对着改造一下

**Comment by jixunmoe** [comment]
看起来已经解决了，关闭该 issue。
